//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/omar.nunez/Downloads/ProjectManager/ProjectManager/Grammar/Parser/ProjectManager.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class ProjectManagerLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SKIPPING=1, PROJECT_LBL=2, DESCRIPTION=3, ITERATION_INDENT=4, JOBS_IDENT=5, 
		ITERATIONS_REFERENCE=6, DURATION_IDENT=7, PRIORITY_IDENT=8, SIZE_IDENT=9, 
		LABELS_INDENT=10, PREDCESSORS_INDENT=11, START_DATE=12, END_DATE=13, MILESTONES_INDENT=14, 
		DOUBLE_SPACED_TEXT=15, DATE=16, NUM=17, TEXT=18, NL=19, WS=20;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"SKIPPING", "PROJECT_LBL", "DESCRIPTION", "ITERATION_INDENT", "JOBS_IDENT", 
		"ITERATIONS_REFERENCE", "DURATION_IDENT", "PRIORITY_IDENT", "SIZE_IDENT", 
		"LABELS_INDENT", "PREDCESSORS_INDENT", "START_DATE", "END_DATE", "MILESTONES_INDENT", 
		"DOUBLE_SPACED_TEXT", "DATE", "NUM", "TEXT", "NL", "WS"
	};


	public ProjectManagerLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ProjectManagerLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "SKIPPING", "PROJECT_LBL", "DESCRIPTION", "ITERATION_INDENT", "JOBS_IDENT", 
		"ITERATIONS_REFERENCE", "DURATION_IDENT", "PRIORITY_IDENT", "SIZE_IDENT", 
		"LABELS_INDENT", "PREDCESSORS_INDENT", "START_DATE", "END_DATE", "MILESTONES_INDENT", 
		"DOUBLE_SPACED_TEXT", "DATE", "NUM", "TEXT", "NL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ProjectManager.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ProjectManagerLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x16', '\xF9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x3', 
		'\x2', '\x6', '\x2', '-', '\n', '\x2', '\r', '\x2', '\xE', '\x2', '.', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x6', '\x5', '=', '\n', '\x5', '\r', '\x5', 
		'\xE', '\x5', '>', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x6', '\x6', 'P', '\n', '\x6', '\r', '\x6', '\xE', '\x6', 
		'Q', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\a', '\b', 'q', '\n', '\b', '\f', '\b', '\xE', 
		'\b', 't', '\v', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '\x82', '\n', '\t', '\f', 
		'\t', '\xE', '\t', '\x85', '\v', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\a', '\n', '\x8F', '\n', '\n', '\f', '\n', '\xE', '\n', '\x92', '\v', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\a', '\r', '\xBA', '\n', '\r', '\f', '\r', '\xE', '\r', '\xBD', '\v', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\xCB', '\n', '\xE', '\f', '\xE', 
		'\xE', '\xE', '\xCE', '\v', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x6', '\x12', '\xED', '\n', '\x12', '\r', '\x12', 
		'\xE', '\x12', '\xEE', '\x3', '\x13', '\x6', '\x13', '\xF2', '\n', '\x13', 
		'\r', '\x13', '\xE', '\x13', '\xF3', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x2', '\x2', '\x16', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '\x3', '\x2', '\a', '\x5', '\x2', '\v', 
		'\v', '\xF', '\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', '\a', '\x2', 
		'\"', '\"', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x4', 
		'\x2', '\f', '\f', '\xF', '\xF', '\x4', '\x2', '\v', '\v', '\"', '\"', 
		'\x2', '\x102', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x3', ',', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x32', '\x3', '\x2', '\x2', '\x2', '\a', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'K', '\x3', '\x2', '\x2', '\x2', '\r', 'X', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\x64', '\x3', '\x2', '\x2', '\x2', '\x11', 'u', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x86', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x17', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\xAB', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\xCF', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '!', '\xE0', '\x3', '\x2', '\x2', 
		'\x2', '#', '\xEC', '\x3', '\x2', '\x2', '\x2', '%', '\xF1', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\xF5', '\x3', '\x2', '\x2', '\x2', ')', '\xF7', '\x3', 
		'\x2', '\x2', '\x2', '+', '-', '\t', '\x2', '\x2', '\x2', ',', '+', '\x3', 
		'\x2', '\x2', '\x2', '-', '.', '\x3', '\x2', '\x2', '\x2', '.', ',', '\x3', 
		'\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', '\x2', '\x2', '/', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\b', '\x2', '\x2', '\x2', 
		'\x31', '\x4', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\a', '%', 
		'\x2', '\x2', '\x33', '\x34', '\x5', '%', '\x13', '\x2', '\x34', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '@', '\x2', '\x2', '\x36', 
		'\x37', '\x5', '%', '\x13', '\x2', '\x37', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x39', '\a', '%', '\x2', '\x2', '\x39', ':', '\a', '%', 
		'\x2', '\x2', ':', '<', '\x3', '\x2', '\x2', '\x2', ';', '=', '\x5', ')', 
		'\x15', '\x2', '<', ';', '\x3', '\x2', '\x2', '\x2', '=', '>', '\x3', 
		'\x2', '\x2', '\x2', '>', '<', '\x3', '\x2', '\x2', '\x2', '>', '?', '\x3', 
		'\x2', '\x2', '\x2', '?', '@', '\x3', '\x2', '\x2', '\x2', '@', '\x41', 
		'\a', 'K', '\x2', '\x2', '\x41', '\x42', '\a', 'v', '\x2', '\x2', '\x42', 
		'\x43', '\a', 'g', '\x2', '\x2', '\x43', '\x44', '\a', 't', '\x2', '\x2', 
		'\x44', '\x45', '\a', '\x63', '\x2', '\x2', '\x45', '\x46', '\a', 'v', 
		'\x2', '\x2', '\x46', 'G', '\a', 'k', '\x2', '\x2', 'G', 'H', '\a', 'q', 
		'\x2', '\x2', 'H', 'I', '\a', 'p', '\x2', '\x2', 'I', 'J', '\a', 'u', 
		'\x2', '\x2', 'J', '\n', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '%', 
		'\x2', '\x2', 'L', 'M', '\a', '%', '\x2', '\x2', 'M', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'P', '\x5', ')', '\x15', '\x2', 'O', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\a', 'L', '\x2', '\x2', 'T', 'U', '\a', 'q', 
		'\x2', '\x2', 'U', 'V', '\a', '\x64', '\x2', '\x2', 'V', 'W', '\a', 'u', 
		'\x2', '\x2', 'W', '\f', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x5', 
		')', '\x15', '\x2', 'Y', 'Z', '\a', 'K', '\x2', '\x2', 'Z', '[', '\a', 
		'v', '\x2', '\x2', '[', '\\', '\a', 'g', '\x2', '\x2', '\\', ']', '\a', 
		't', '\x2', '\x2', ']', '^', '\a', '\x63', '\x2', '\x2', '^', '_', '\a', 
		'v', '\x2', '\x2', '_', '`', '\a', 'k', '\x2', '\x2', '`', '\x61', '\a', 
		'q', '\x2', '\x2', '\x61', '\x62', '\a', 'p', '\x2', '\x2', '\x62', '\x63', 
		'\a', '<', '\x2', '\x2', '\x63', '\xE', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\x5', ')', '\x15', '\x2', '\x65', '\x66', '\a', '\x46', '\x2', 
		'\x2', '\x66', 'g', '\a', 'w', '\x2', '\x2', 'g', 'h', '\a', 't', '\x2', 
		'\x2', 'h', 'i', '\a', '\x63', '\x2', '\x2', 'i', 'j', '\a', 'v', '\x2', 
		'\x2', 'j', 'k', '\a', 'k', '\x2', '\x2', 'k', 'l', '\a', 'q', '\x2', 
		'\x2', 'l', 'm', '\a', 'p', '\x2', '\x2', 'm', 'n', '\a', '<', '\x2', 
		'\x2', 'n', 'r', '\x3', '\x2', '\x2', '\x2', 'o', 'q', '\x5', ')', '\x15', 
		'\x2', 'p', 'o', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x3', '\x2', '\x2', 
		'\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', 
		'\x2', 's', '\x10', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'v', '\x5', ')', '\x15', '\x2', 'v', 'w', '\a', 'R', 
		'\x2', '\x2', 'w', 'x', '\a', 't', '\x2', '\x2', 'x', 'y', '\a', 'k', 
		'\x2', '\x2', 'y', 'z', '\a', 'q', '\x2', '\x2', 'z', '{', '\a', 't', 
		'\x2', '\x2', '{', '|', '\a', 'k', '\x2', '\x2', '|', '}', '\a', 'v', 
		'\x2', '\x2', '}', '~', '\a', '{', '\x2', '\x2', '~', '\x7F', '\a', '<', 
		'\x2', '\x2', '\x7F', '\x83', '\x3', '\x2', '\x2', '\x2', '\x80', '\x82', 
		'\x5', ')', '\x15', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x85', '\x3', '\x2', '\x2', '\x2', '\x83', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x87', '\x5', ')', '\x15', '\x2', '\x87', '\x88', '\a', 'U', 
		'\x2', '\x2', '\x88', '\x89', '\a', 'k', '\x2', '\x2', '\x89', '\x8A', 
		'\a', '|', '\x2', '\x2', '\x8A', '\x8B', '\a', 'g', '\x2', '\x2', '\x8B', 
		'\x8C', '\a', '<', '\x2', '\x2', '\x8C', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8F', '\x5', ')', '\x15', '\x2', '\x8E', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x92', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x91', '\x14', '\x3', '\x2', '\x2', '\x2', '\x92', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x94', '\x5', ')', '\x15', '\x2', '\x94', 
		'\x95', '\a', 'N', '\x2', '\x2', '\x95', '\x96', '\a', '\x63', '\x2', 
		'\x2', '\x96', '\x97', '\a', '\x64', '\x2', '\x2', '\x97', '\x98', '\a', 
		'g', '\x2', '\x2', '\x98', '\x99', '\a', 'n', '\x2', '\x2', '\x99', '\x9A', 
		'\a', 'u', '\x2', '\x2', '\x9A', '\x9B', '\a', '<', '\x2', '\x2', '\x9B', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\x5', ')', '\x15', 
		'\x2', '\x9D', '\x9E', '\a', 'R', '\x2', '\x2', '\x9E', '\x9F', '\a', 
		't', '\x2', '\x2', '\x9F', '\xA0', '\a', 'g', '\x2', '\x2', '\xA0', '\xA1', 
		'\a', '\x66', '\x2', '\x2', '\xA1', '\xA2', '\a', 'g', '\x2', '\x2', '\xA2', 
		'\xA3', '\a', '\x65', '\x2', '\x2', '\xA3', '\xA4', '\a', 'g', '\x2', 
		'\x2', '\xA4', '\xA5', '\a', 'u', '\x2', '\x2', '\xA5', '\xA6', '\a', 
		'u', '\x2', '\x2', '\xA6', '\xA7', '\a', 'q', '\x2', '\x2', '\xA7', '\xA8', 
		'\a', 't', '\x2', '\x2', '\xA8', '\xA9', '\a', 'u', '\x2', '\x2', '\xA9', 
		'\xAA', '\a', '<', '\x2', '\x2', '\xAA', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAC', '\x5', ')', '\x15', '\x2', '\xAC', '\xAD', '\a', 
		'U', '\x2', '\x2', '\xAD', '\xAE', '\a', 'v', '\x2', '\x2', '\xAE', '\xAF', 
		'\a', '\x63', '\x2', '\x2', '\xAF', '\xB0', '\a', 't', '\x2', '\x2', '\xB0', 
		'\xB1', '\a', 'v', '\x2', '\x2', '\xB1', '\xB2', '\a', '\"', '\x2', '\x2', 
		'\xB2', '\xB3', '\a', '\x46', '\x2', '\x2', '\xB3', '\xB4', '\a', '\x63', 
		'\x2', '\x2', '\xB4', '\xB5', '\a', 'v', '\x2', '\x2', '\xB5', '\xB6', 
		'\a', 'g', '\x2', '\x2', '\xB6', '\xB7', '\a', '<', '\x2', '\x2', '\xB7', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBA', '\x5', ')', '\x15', 
		'\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x5', 
		')', '\x15', '\x2', '\xBF', '\xC0', '\a', 'G', '\x2', '\x2', '\xC0', '\xC1', 
		'\a', 'p', '\x2', '\x2', '\xC1', '\xC2', '\a', '\x66', '\x2', '\x2', '\xC2', 
		'\xC3', '\a', '\"', '\x2', '\x2', '\xC3', '\xC4', '\a', '\x46', '\x2', 
		'\x2', '\xC4', '\xC5', '\a', '\x63', '\x2', '\x2', '\xC5', '\xC6', '\a', 
		'v', '\x2', '\x2', '\xC6', '\xC7', '\a', 'g', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', '<', '\x2', '\x2', '\xC8', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'\xCB', '\x5', ')', '\x15', '\x2', '\xCA', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD0', '\x5', ')', '\x15', '\x2', '\xD0', '\xD1', '\a', 
		'O', '\x2', '\x2', '\xD1', '\xD2', '\a', 'k', '\x2', '\x2', '\xD2', '\xD3', 
		'\a', 'n', '\x2', '\x2', '\xD3', '\xD4', '\a', 'g', '\x2', '\x2', '\xD4', 
		'\xD5', '\a', 'u', '\x2', '\x2', '\xD5', '\xD6', '\a', 'v', '\x2', '\x2', 
		'\xD6', '\xD7', '\a', 'q', '\x2', '\x2', '\xD7', '\xD8', '\a', 'p', '\x2', 
		'\x2', '\xD8', '\xD9', '\a', 'g', '\x2', '\x2', '\xD9', '\xDA', '\a', 
		'u', '\x2', '\x2', '\xDA', '\xDB', '\a', '<', '\x2', '\x2', '\xDB', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', '\x5', ')', '\x15', '\x2', 
		'\xDD', '\xDE', '\x5', ')', '\x15', '\x2', '\xDE', '\xDF', '\x5', '%', 
		'\x13', '\x2', '\xDF', ' ', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', 
		'\t', '\x3', '\x2', '\x2', '\xE1', '\xE2', '\t', '\x3', '\x2', '\x2', 
		'\xE2', '\xE3', '\t', '\x3', '\x2', '\x2', '\xE3', '\xE4', '\t', '\x3', 
		'\x2', '\x2', '\xE4', '\xE5', '\a', '/', '\x2', '\x2', '\xE5', '\xE6', 
		'\t', '\x3', '\x2', '\x2', '\xE6', '\xE7', '\t', '\x3', '\x2', '\x2', 
		'\xE7', '\xE8', '\a', '/', '\x2', '\x2', '\xE8', '\xE9', '\t', '\x3', 
		'\x2', '\x2', '\xE9', '\xEA', '\t', '\x3', '\x2', '\x2', '\xEA', '\"', 
		'\x3', '\x2', '\x2', '\x2', '\xEB', '\xED', '\t', '\x3', '\x2', '\x2', 
		'\xEC', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEE', '\x3', '\x2', 
		'\x2', '\x2', '\xEE', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEF', 
		'\x3', '\x2', '\x2', '\x2', '\xEF', '$', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xF2', '\t', '\x4', '\x2', '\x2', '\xF1', '\xF0', '\x3', '\x2', '\x2', 
		'\x2', '\xF2', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF1', '\x3', 
		'\x2', '\x2', '\x2', '\xF3', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF4', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF6', '\t', '\x5', '\x2', '\x2', 
		'\xF6', '(', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF8', '\t', '\x6', 
		'\x2', '\x2', '\xF8', '*', '\x3', '\x2', '\x2', '\x2', '\r', '\x2', '.', 
		'>', 'Q', 'r', '\x83', '\x90', '\xBB', '\xCC', '\xEE', '\xF3', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
